flags:
  text:
    integer-simple: false
packages:
- ./
- location:
    git: https://github.com/GaloisInc/ivory.git
    extra-dep: true
    commit: a6ba4cb852bddded6117b2d0c48574663f39f469
  subdirs:
  - ivory-stdlib
  - ivory-model-check
  - ivory-opts
  - ivory-examples
  - ivory-serialize
  - ivory
  - ivory-hw
  - ivory-eval
  - ivory-backend-c
  - ivory-quickcheck
  - ivory-artifact
- location:
    git: https://github.com/GaloisInc/ivory-backend-acl2.git
    commit: fa6667b29d24da34e7f35448d7598cd704dde9ec
extra-deps:
- HStringTemplate-0.8.3
- QuickCheck-2.8.1
- acl2-0.0.1
- blaze-builder-0.4.0.1
- cpphs-1.19
- data-reify-0.6.1
- dlist-0.7.1.1
- exception-mtl-0.4
- exception-transformers-0.4.0.1
- fgl-5.5.1.0
- ghc-srcspan-plugin-0.2.1.0
- hashable-1.2.3.3
- haskell-src-exts-1.16.0.1
- haskell-src-meta-0.6.0.10
- language-c-quote-0.11
- mainland-pretty-0.4.0.0
- monadLib-3.7.3
- mtl-2.2.1
- nats-1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.9
- polyparse-1.11
- primitive-0.6
- random-1.1
- safe-0.3.9
- semigroups-0.16.2.2
- srcloc-0.5.0.2
- stm-2.4.4
- syb-0.5.1
- symbol-0.2.4
- text-1.2.1.1
- tf-random-0.5
- th-expand-syns-0.3.0.6
- th-lift-0.7.2
- th-orphans-0.12.2
- th-reify-many-0.1.3
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- utf8-string-1
- void-0.7
resolver: ghc-7.10
